const whatsapp = "https://wa.me/91YOURNUMBER?text=Hi%20Peak%20Web%20Studio%2C%20I%27m%20interested%20in%20a%20website.";
const concepts = [
 { number:"01", type:"BARBER & GROOMING", name:"The Modern Barber", description:"A bold, appointment-ready online home for a barbershop.", className:"barber", title:<>CUT<br/><i>ABOVE.</i></> },
 { number:"02", type:"BEAUTY & SALON", name:"Aura Studio", description:"An elegant service menu that turns visitors into bookings.", className:"salon", title:<>aura<span>beauty studio</span></> },
 { number:"03", type:"CAFÉ & HOSPITALITY", name:"The Daily Grind", description:"A warm, polished first impression for a neighbourhood café.", className:"cafe", title:<>the daily<br/><i>grind.</i></> }
];
export default function Home() {
 return <main>
  <nav className="nav wrap"><a className="brand" href="#"><span className="brand-mark">P.</span><span>PEAK<small>WEB STUDIO</small></span></a><div className="nav-links"><a href="#work">Our work</a><a href="#services">Services</a><a href="#process">Process</a></div><a className="nav-cta" href={whatsapp} target="_blank" rel="noreferrer">Let’s talk ↗</a></nav>
  <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="dot"/> INDEPENDENT WEB DESIGN · DEHRADUN, INDIA</div><h1>Your business<br/>deserves to look<br/><em>like the best.</em></h1><p className="hero-text">I build clean, modern websites that help local businesses get noticed, earn trust, and turn curious visitors into customers.</p><div className="hero-actions"><a className="button primary" href={whatsapp} target="_blank" rel="noreferrer">Build my website ↗</a><a className="text-link" href="#work">Explore sample work ↓</a></div><div className="proof"><span className="proof-icon">✂</span><p><strong>Made for local business.</strong><br/>Personal service, thoughtful design.</p></div></div>
  <div className="hero-art"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="browser"><div className="browser-bar"><span/><span/><span/><b>yourbusiness.in</b></div><div className="browser-content"><div className="tiny">GOOD BUSINESS. GREAT FIRST IMPRESSION.</div><div className="mock-title">Make them<br/><i>remember</i> you.</div><div className="mock-line"/><span className="mock-btn">DISCOVER MORE ↗</span><div className="sun"/><div className="mock-caption">DESIGNED TO STAND OUT</div></div></div><div className="float-card"><span>↗</span><div><strong>First impressions</strong><small>Start right here.</small></div></div><div className="stamp">LOCAL<br/>BUSINESS<br/><b>↗</b></div></div>
  <div className="hero-bottom"><span>DESIGNED WITH PURPOSE</span><span>BUILT FOR MOBILE</span><span>MADE FOR YOUR NEXT CHAPTER ↘</span></div></section>
  <div className="ticker">BARBERSHOPS <b>✳</b> SALONS <b>✳</b> CAFÉS <b>✳</b> GYMS <b>✳</b> NEW BUSINESSES <b>✳</b> LOCAL BRANDS <b>✳</b></div>
  <section className="section wrap" id="work"><div className="section-head"><div><div className="eyebrow">01 / SELECTED CONCEPTS</div><h2>Imagine your business<br/><em>looking this good.</em></h2></div><p>These are sample concepts—not client projects. Your website will be designed around your business, your customers, and your goals.</p></div>
  <div className="project-grid">{concepts.map(item=><article className="project" key={item.number}><div className={"project-visual "+item.className}><div className="project-top"><span>DEMO CONCEPT</span><span>{item.number} / 03</span></div><div className="concept-title">{item.title}</div>{item.className==="barber"&&<div className="scissors">✂</div>}{item.className==="salon"&&<div className="flower">✳</div>}{item.className==="cafe"&&<div className="coffee-mark">D<span>G</span></div>}<div className="visual-foot">{item.className==="barber"?"THE MODERN BARBER · EST. 2025":item.className==="salon"?"YOUR MOMENT. YOUR GLOW.":"GOOD COFFEE. GOOD COMPANY."}</div></div><div className="project-info"><div><div className="project-type">{item.type}</div><h3>{item.name}</h3><p>{item.description}</p></div><a href={whatsapp} target="_blank" rel="noreferrer" aria-label={"Ask about "+item.name}>↗</a></div></article>)}</div></section>
  <section className="services" id="services"><div className="wrap services-inner"><div><div className="eyebrow">02 / WHAT I CAN BUILD</div><h2>A website that<br/>works as hard as <em>you do.</em></h2><p className="service-intro">No confusing tech talk. Just a professional online presence built around what your business needs.</p><a className="button light" href={whatsapp} target="_blank" rel="noreferrer">Let’s discuss your idea ↗</a></div><div className="service-list"><div className="service-row"><span>01</span><div><h3>Business websites</h3><p>Showcase your story, services, location and contact details in one polished place.</p></div><b>↗</b></div><div className="service-row"><span>02</span><div><h3>Barber & salon sites</h3><p>Service menus, gallery, opening hours and easy appointment enquiries.</p></div><b>↗</b></div><div className="service-row"><span>03</span><div><h3>New business launch</h3><p>Look established from day one with a brand-matched, mobile-first website.</p></div><b>↗</b></div><div className="service-row"><span>04</span><div><h3>Landing pages</h3><p>A focused page for a promotion, new service, event or local campaign.</p></div><b>↗</b></div></div></div></section>
  <section className="section wrap process" id="process"><div className="eyebrow">03 / SIMPLE FROM START TO LAUNCH</div><h2>Good work. <em>No guesswork.</em></h2><div className="steps"><div><span>01</span><h3>Tell me about it</h3><p>We discuss your business, audience, and what you want your site to achieve.</p></div><div><span>02</span><h3>Design & build</h3><p>I create a tailored design and make sure it looks great on phones and computers.</p></div><div><span>03</span><h3>Go live</h3><p>After your review, we publish your site and make it easy to share with customers.</p></div></div></section>
  <section className="cta-section"><div className="wrap cta-box"><div className="eyebrow">YOUR NEXT CHAPTER STARTS ONLINE</div><h2>Ready to make a<br/><em>stronger first impression?</em></h2><p>Tell me what you’re building. Let’s make a website that gives people a reason to choose you.</p><a className="button primary" href={whatsapp} target="_blank" rel="noreferrer">Start a conversation ↗</a><small>Dehradun · Rishikesh · Haridwar · Uttarakhand</small></div></section>
  <footer className="footer wrap"><a className="brand" href="#"><span className="brand-mark">P.</span><span>PEAK<small>WEB STUDIO</small></span></a><p>Thoughtful websites for ambitious local businesses.</p><div><a href="#work">Work</a><a href="#services">Services</a><a href={whatsapp} target="_blank" rel="noreferrer">WhatsApp ↗</a></div><span className="copyright">© 2026 PEAK WEB STUDIO</span></footer>
 </main>;
}
